#
# You will need a license from https://funkemunky.cc/shop to use the AntiVPN to its full potential.
# Your server will have 200 free queries per month. Once that ends, the plugin will no longer query.
# You can also use your Kauri Anticheat license here.
#
license: ""
#
# Caching Database #
# Types: Mongo, Flatfile, MySQL.
#
# FLATFILE INFORMATION #
# Flatfile is enabled by default if nothing else is enabled.
# Make sure to only enable one at a time or plugin will default to Flatfile.
# The database will be stored in the root directory of the user that started the server.
# Each entry will be stored as a .json file in the directory with the ID of as its name.
# (user directory)/CarbonFFDBs/{database}
#
# MONGO INFORMATION #
# For Mongo, leave credentials empty if your mongo instance doesn't require it.
# The authDatabase is used if your mongo credentials are tied to a different database.
#
# MYSQL INFORMATION #
# It is recommended you turn SSL to true for secure transfer of information.
#
# GENERAL INFORMATION #
# It is highly recommended you leave the hashIp setting to true and the hash algorithm to SHA2.
# Hash Options: CRC16, SHA1, SHA2, Argon.
# This will hash the IPs into a SHA1 or SHA2 string to protect your users privacy.
# More information on SHA-2: https://en.wikipedia.org/wiki/SHA-2
database:
  flatfile:
    enabled: true
    database: "kaurivpn"
  mongo:
    enabled: false
    ip: "127.0.0.1"
    port: 27017
    username: ""
    password: ""
    database: "kaurivpn"
    authDatabase: ""
  mysql:
    enabled: false
    ip: "127.0.0.1"
    port: 3306
    username: "root"
    password: "password"
    database: "kaurivpn"
    ssl: true
  general:
    hashIp: true
    hashType: "SHA2"
# Enable kicking #
# You can disable the function of removing players from the server.
kick-players: true
# Kick Message #
# The message sent to the player when they are kicked.
kick-message: |-
  &r
  &6&lKauri AntiVPN
  &7You have been kicked for using a VPN.
  &r
  &f&o%method%
#
# Run Command in Bungee #
# This will allow the command to be run in Bungee.
kick-bungee: false
#
# Kick Commands #
# These will be run on player kicks.
kick-commands: []
#
# VPN Use Alerts #
# A great way to find nefarious players quickly (i.e. cheaters) without them knowing what is going on.
alert-staff: true
#
# Alert Message #
# This will be the message sent to staff vpn detection.
# Requires the permission antivpn.alert to view alerts.
alert-message: "&8[&c!&8] &7Found &f%player% &7to be using a VPN."
# Alert Hover #
# The lines here will be shown when hovering on the alert message
# Placeholders: %method%, %ip%, %countryCode%, %countryName%, %score%, %queriesLeft%, %proxy%, %isp%, %timeZone%
alert-hover:
  - "&eMethod: &f%method%"
  - "&eIP: &f%ip%"
  - "&eCountry: &f%countryName%"
#
# Alert Bungee #
# Requires AntiVPN to be on all servers using it and will require Atlas bungee mode to be enabled.
# All configuration for alerts is local. No setup required on Bungee.
alert-bungee: false
#
# Hide IP #
# This will hide the IP from all users. If false, IPs are only shown to users with permission antivpn.showip.
hide-ips: false
#
# Fire Event #
# If disabled, the VPNCheckEvent will no longer be fired. Only disable this if you have no plugins depending on it.
fire-event: true