name: KauriVPN
main: dev.brighten.pl.AntiVPN
author: funkemunky
depend: [Atlas]
version: ${project.version}
permissions:
  antivpn.showip:
    default: false
    description: Permission node to show IPs.